- alias: Arrive home
  initial_state: true
  trigger:
    platform: state
    entity_id: device_tracker.tonissphone, device_tracker.liisiiphone
    from: 'not_home'
    to: 'home'
    #for:
    #  hours: 0
    #  minutes: 1
    #  seconds: 0
  action:
    service: scene.turn_on
    entity_id: scene.arrive_home
