- alias: Arrive home boolean
  initial_state: true
  trigger:
    platform: template
    value_template: "{% if (is_state('device_tracker.tonissiphone','home')) or (is_state('device_tracker.liisiiphone','home')) %}true{% endif %}"
  action:
    service: input_boolean.turn_on
    entity_id: input_boolean.someone_at_home

- alias: Arrive home
  initial_state: true
  trigger:
    platform: state
    entity_id: input_boolean.someone_at_home
    to: "on"
  action:
    service: scene.turn_on
    entity_id: scene.arrive_home
