- alias: Turn on bathroom light when motion detected
  initial_state: true
  hide_entity: true
  trigger:
    - platform: state
      entity_id: sensor.bathroom_multisensor_burglar
      to: '8'
  condition:
    condition: numeric_state
    entity_id: sensor.bathroom_multisensor_luminance
    below: '2'
  action:
    service: script.turn_on
    entity_id: script.bathroom_timed_light

- alias: Turn off bathroom light when motion ends
  initial_state: true
  hide_entity: true
  trigger:
    - platform: state
      entity_id: sensor.bathroom_multisensor_burglar
      to: '0'
  action:
    service: script.turn_on
    entity_id: script.bathroom_light_delay
