- alias: Turn on bathroom fan when humidity is high
  hide_entity: true
  trigger:
    - platform: numeric_state
      entity_id: sensor.aeotec_zw100_multisensor_6_relative_humidity_3_5
      above: 50
  action:
    service: script.turn_on
    entity_id: script.bathroom_fan
