- alias: Turn on bathroom fan when humidity is high
  initial_state: true
  hide_entity: true
  trigger:
    - platform: numeric_state
      entity_id: sensor.bathroom_multisensor_relative_humidity
      above: 50
  action:
    service: switch.turn_on
    entity_id: switch.bathroom_fan_ceiling

- alias: Turn off bathroom fan when humidity is low
  initial_state: true
  hide_entity: true
  trigger:
    - platform: numeric_state
      entity_id: sensor.bathroom_multisensor_relative_humidity
      below: 50
  action:
    service: switch.turn_off
    entity_id: switch.bathroom_fan_ceiling
