- alias: Turn on bathroom fan when humidity is high
  hide_entity: true
  trigger:
    - platform: numeric_state
      entity_id: sensor.aeotec_zw100_multisensor_6_relative_humidity_3_5
      above: 50
  action:
    service: switch.turn_on
    entity_id: switch.fibaro_system_fgs222_double_relay_switch_2x15kw_switch_13_0

- alias: Turn off bathroom fan when humidity is low
  hide_entity: true
  trigger:
    - platform: numeric_state
      entity_id: sensor.aeotec_zw100_multisensor_6_relative_humidity_3_5
      below: 50
  action:
    service: switch.turn_off
    entity_id: switch.fibaro_system_fgs222_double_relay_switch_2x15kw_switch_13_0
