- alias: Turn ceiling lights on when motion is detected
  hide_entity: true
  trigger:
    - platform: state
      entity_id: sensor.aeotec_zw100_multisensor_6_burglar_12_10
      to: '8'
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.aeotec_zw100_multisensor_6_luminance_12_3
        below: '2'
      - condition: time
        before: '22:00:00'
        after: '09:00:00'
  action:
    service: switch.turn_on
    entity_id: switch.fibaro_system_fgs222_double_relay_switch_2x15kw_switch_6_0


- alias: Turn off bedroom light after n minutes
  hide_entity: true
  trigger:
    - platform: state
      entity_id: sensor.aeotec_zw100_multisensor_6_burglar_12_10
      to: '0'
  action:
    - alias: Wait n minutes
      delay:
        minutes: 5
    - service: switch.turn_off
      entity_id: switch.fibaro_system_fgs222_double_relay_switch_2x15kw_switch_6_0

- alias: Turn lights on at morning
  hide_entity: true
  trigger:
    - platform: time
      after: '8:30'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.turn_wakeup_lights_on
        state: 'on'
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
  action:
    service: light.turn_on
    entity_id: light.bedroom_reading
