- alias: Turn ceiling lights on when motion is detected
  initial_state: true
  hide_entity: true
  trigger:
    - platform: state
      entity_id: sensor.bedroom_multisensor_burglar
      to: '8'
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.bedroom_multisensor_luminance
        below: '2'
      - condition: time
        before: '22:00:00'
        after: '09:00:00'
  action:
    service: switch.turn_on
    entity_id: switch.bedroom_lights_ceiling


- alias: Turn off bedroom light after n minutes
  initial_state: true
  hide_entity: true
  trigger:
    - platform: state
      entity_id: sensor.bedroom_multisensor_burglar
      to: '0'
  action:
    - alias: Wait n minutes
      delay:
        minutes: 5
    - service: switch.turn_off
      entity_id: switch.bedroom_lights_ceiling

- alias: Turn lights on at morning
  initial_state: true
  hide_entity: true
  trigger:
    - platform: time
      at: '8:30:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.turn_wakeup_lights_on
        state: 'on'
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
  action:
    service: light.turn_on
    entity_id: light.bedroom_reading
