- alias: Turn off bedroom light after n minutes
  hide_entity: true
  trigger:
    - platform: state
      entity_id: switch.fibaro_system_fgs222_double_relay_switch_2x15kw_switch_6_0
      to: 'on'
  action:
    service: script.turn_on
    entity_id: script.bedroom_light_delay

- alias: Turn lights on at morning
  hide_entity: true
  trigger:
    - platform: time
      after: '8:30'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.turn_wakeup_lights_on
        state: 'on'
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
  action:
    service: light.turn_on
    entity_id: light.bedroom_reading

- alias: Turn ceiling lights on when motion is detected
  hide_entity: true
  trigger:
    - platform: state
      entity_id: sensor.aeotec_zw100_multisensor_6_burglar_12_10
      to: '8'
  condition:
    condition: numeric_state
    entity_id: sensor.aeotec_zw100_multisensor_6_luminance_12_3
    below: '2'
  action:
    service: switch.turn_on
    entity_id: switch.fibaro_system_fgs222_double_relay_switch_2x15kw_switch_6_0


# - alias: Turn on bedroom ceiling light when motion detected
#  hide_entity: true
#  trigger:
#    - platform: state
#      entity_id: sensor.aeotec_zw100_multisensor_6_burglar_12_10
#      to: '8'
#  action:
#    service: script.turn_on
#    entity_id: script.bedroom_timed_light

#- alias: Turn off bedroom ceiling light when motion ends
#  hide_entity: true
#  trigger:
#    - platform: state
#      entity_id: sensor.aeotec_zw100_multisensor_6_burglar_12_10
#      to: '0'
#  action:
#    service: script.turn_on
#    entity_id: script.bedroom_ceiling_light_delay
