- alias: Turn christmas lights on
  hide_entity: true
  trigger:
    - platform: sun
      event: sunset
      offset: '+01:00:00'
  action: 
    service: light.turn_on
    entity_id: light.christmas_lights
    
- alias: Turn christmas lights off
  hide_entity: true
  trigger:
    - platform: sun
      event: sunrise
      offset: '+01:00:00'
  action: 
    service: light.turn_off
    entity_id: light.christmas_lights