- alias: Turn good morning scene on automatically
  hide_entity: true
  trigger:
    - platform: time
      after: '8:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.turn_on_auto_good_morning
        state: 'on'
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
  action:
    service: scene.turn_on
    entity_id: scene.good_morning
