- alias: Turn on herbie lights when everything in living room goes off
  initial_state: false
  hide_entity: true
  trigger:
    - platform: state
      entity_id: group.living_room
      to: 'off'
  condition:
    condition: time
    after: '02:00:00'
    before: '08:00:00'
  action:
    service: light.turn_on
    entity_id: light.herbie_light

- alias: Turn on herbie lights when kitchen lights is fully bright
  initial_state: false
  hide_entity: true
  trigger:
    - platform: numeric_state
      value_template: '{{ state.attributes.brightness }}'
      entity_id: light.fibaro_system_fgrgbwm441_rgbw_controller_level_9_0_6
      above: 250
  action:
    service: light.turn_on
    entity_id: light.herbie_light

- alias: Turn on herbie lights when bedroom action ends
  initial_state: false
  hide_entity: true
  trigger:
    - platform: state
      entity_id: sensor.aeotec_zw100_multisensor_6_burglar_12_10
      to: '0'
  condition:
    condition: time
    after: '02:00:00'
    before: '05:00:00'
  action:
    service: light.turn_on
    entity_id: light.herbie_light

- alias: Turn off herbie lights when bedroom has action
  initial_state: false
  hide_entity: true
  trigger:
    - platform: state
      entity_id: sensor.aeotec_zw100_multisensor_6_burglar_12_10
      to: '8'
  condition:
    condition: time
    after: '02:00:00'
    before: '07:00:00'
  action:
    service: light.turn_off
    entity_id: light.herbie_light

- alias: Turn off herbie lights when kitchen lights is dimmed
  initial_state: false
  hide_entity: true
  trigger:
    - platform: numeric_state
      value_template: '{{ state.attributes.brightness }}'
      entity_id: light.fibaro_system_fgrgbwm441_rgbw_controller_level_9_0_6
      below: 250
  action:
    service: light.turn_off
    entity_id: light.herbie_light

- alias: Turn off herbie lights when kitchen lights is off
  initial_state: false
  hide_entity: true
  trigger:
    - platform: state
      entity_id: light.fibaro_system_fgrgbwm441_rgbw_controller_level_9_0_6
      to: 'off'
  condition:
    condition: time
    after: '18:00:00'
    before: '01:00:00'
  action:
    service: light.turn_off
    entity_id: light.herbie_light
