- alias: Turn on herbie lights when everything in living room is off
  hide_entity: true
  trigger:
    - platform: state
      entity_id: group.living_room
      to: 'off'
  action:
    service: light.turn_on
    entity_id: light.herbie_light

- alias: Turn off herbie lights when living room has lights on
  hide_entity: true
  trigger:
    - platform: state
      entity_id: group.living_room
      to: 'on'
  action:
    service: light.turn_off
    entity_id: light.herbie_light

- alias: Turn off herbie lights when bedroom has action
  hide_entity: true
  trigger:
    - platform: state
      entity_id: sensor.aeotec_zw100_multisensor_6_burglar_12_10
      to: '8'
  action:
    service: light.turn_off
    entity_id: light.herbie_light
