- alias: Tõnis leave home
  initial_state: true
  trigger:
    platform: state
    entity_id: device_tracker.tonissphone
    from: 'home'
    to: 'not_home'
  condition:
    condition: state
    entity_id: device_tracker.liisiiphone
    state: 'not_home'
  action:
    service: scene.turn_on
    entity_id: scene.leave_home

- alias: Liisi leave home
  initial_state: true
  trigger:
    platform: state
    entity_id: device_tracker.liisiiphone
    from: 'home'
    to: 'not_home'
  condition:
    condition: state
    entity_id: device_tracker.tonissphone
    state: 'not_home'
  action:
    service: scene.turn_on
    entity_id: scene.leave_home
