- alias: Leave home boolean
  initial_state: true
  trigger:
    platform: template
    value_template: "{% if (is_state('device_tracker.tonissiphone','not_home')) and (is_state('device_tracker.liisiiphone','not_home')) %}true{% endif %}"
  action:
    service: input_boolean.turn_off
    entity_id: input_boolean.someone_at_home

- alias: Leave home
  initial_state: true
  trigger:
    platform: state
    entity_id: input_boolean.someone_at_home
    to: "off"
  action:
    service: scene.turn_on
    entity_id: scene.leave_home
