- alias: Turn on automatically close window covers
  initial_state: false
  trigger:
    - platform: sun
      event: sunset
      offset: '+01:00:00'
  action:
    service: cover.close_cover
    entity_id: cover.livingroom_windowshade

- alias: Turn on automatically open window covers
  initial_state: false
  trigger:
    - platform: sun
      event: sunrise
      offset: '-01:00:00'
  action:
    service: cover.open_cover
    entity_id: cover.livingroom_windowshade
